-- MySQL Script generated by MySQL Workbench
-- Wed Feb  4 23:55:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `email_verified_at` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `remember_toke` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `guard_name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `guard_name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions_has_roles` (
  `permissions_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`permissions_id`, `roles_id`),
  INDEX `fk_permissions_has_roles_roles1_idx` (`roles_id` ASC) VISIBLE,
  INDEX `fk_permissions_has_roles_permissions_idx` (`permissions_id` ASC) VISIBLE,
  CONSTRAINT `fk_permissions_has_roles_permissions`
    FOREIGN KEY (`permissions_id`)
    REFERENCES `mydb`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permissions_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles_has_users` (
  `roles_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `model_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roles_id`, `users_id`),
  INDEX `fk_roles_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_roles_has_users_roles1_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_has_users_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensors` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `is_active` TINYINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensors_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensors_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensor_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensor_tokens` (
  `id` INT NOT NULL,
  `sensor_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `frefix` VARCHAR(10) NOT NULL,
  `hash` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `rate_limit` VARCHAR(45) NOT NULL,
  `last_used_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensor_tokens_sensors1_idx` (`sensor_id` ASC) VISIBLE,
  INDEX `fk_sensor_tokens_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_tokens_sensors1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `mydb`.`sensors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor_tokens_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensor_latest_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensor_latest_state` (
  `sensor_id` INT NULL,
  `sensor_token_id` INT NOT NULL,
  `received_at` DATETIME NULL,
  `value` JSON NULL,
  PRIMARY KEY (`sensor_id`),
  INDEX `fk_sensor_latest_state_sensor_tokens1_idx` (`sensor_token_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_latest_state_sensors1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `mydb`.`sensors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor_latest_state_sensor_tokens1`
    FOREIGN KEY (`sensor_token_id`)
    REFERENCES `mydb`.`sensor_tokens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensor_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensor_fields` (
  `id` INT NOT NULL,
  `sensor_id` INT NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  `sort_order` INT NULL,
  `is_required` TINYINT NOT NULL,
  `description` VARCHAR(255) NULL,
  `min_value` DOUBLE NULL,
  `max_value` DOUBLE NULL,
  `unit` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensor_fields_sensors1_idx` (`sensor_id` ASC) VISIBLE,
  UNIQUE INDEX `sensor_id_UNIQUE` (`sensor_id` ASC) VISIBLE,
  UNIQUE INDEX `key_UNIQUE` (`key` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_fields_sensors1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `mydb`.`sensors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`measurements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`measurements` (
  `id` INT NOT NULL,
  `sensor_id` INT NOT NULL,
  `sensor_token_id` INT NOT NULL,
  `received_at` DATETIME NOT NULL,
  `raw_payload` JSON NOT NULL,
  `is_valid` TINYINT NOT NULL,
  `source_ip` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensor_submissions_sensors1_idx` (`sensor_id` ASC) VISIBLE,
  INDEX `fk_sensor_submissions_sensor_tokens1_idx` (`sensor_token_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_submissions_sensors1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `mydb`.`sensors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor_submissions_sensor_tokens1`
    FOREIGN KEY (`sensor_token_id`)
    REFERENCES `mydb`.`sensor_tokens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`measurement_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`measurement_values` (
  `id` INT NOT NULL,
  `measurement_id` INT NOT NULL,
  `sensor_field_id` INT NOT NULL,
  `value` JSON NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_measurement_values_measurements1_idx` (`measurement_id` ASC) VISIBLE,
  INDEX `fk_measurement_values_sensor_fields1_idx` (`sensor_field_id` ASC) VISIBLE,
  CONSTRAINT `fk_measurement_values_measurements1`
    FOREIGN KEY (`measurement_id`)
    REFERENCES `mydb`.`measurements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_measurement_values_sensor_fields1`
    FOREIGN KEY (`sensor_field_id`)
    REFERENCES `mydb`.`sensor_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensor_shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensor_shares` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `sensor_id` INT NOT NULL,
  `permission` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_accepted` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensor_shares_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_sensor_shares_sensors1_idx` (`sensor_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `sensor_id_UNIQUE` (`sensor_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_shares_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor_shares_sensors1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `mydb`.`sensors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
